# Generated by Django 4.2 on 2023-04-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
